name: CI
on:
  push:
    branches: [master, ci]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Check SPDX identifiers
        run: ./scripts/lint/spdx.sh

      - name: Check indentation
        run: ./scripts/lint/indent.sh

      - name: Check formatting
        run: ./scripts/lint/02-clang-format.sh

      - name: Check shell scripts
        run: ./scripts/lint/03-shellcheck.sh

  tool:
    strategy:
      matrix:
        include:
          - features:
          - features: --no-default-features --features="redox_hwio"

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: Build tool
        run: cargo build ${{ matrix.features }} --release --manifest-path tool/Cargo.toml

  ec:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - vendor: novacustom
            board: nv4x_tgl
          - vendor: novacustom
            board: ns5x_tgl
          - vendor: novacustom
            board: nv4x_adl
          - vendor: novacustom
            board: ns5x_adl

    steps:
      - uses: actions/checkout@v3

      - name: Build firmware
        run: EC_BOARD_VENDOR=${{ matrix.vendor }} EC_BOARD_MODEL=${{ matrix.model }} ./build.sh
