name: CI
on:
  push:
    branches: [master, ci]
  pull_request:

jobs:
  tool:
    strategy:
      matrix:
        include:
          - features:
          - features: --no-default-features --features="redox_hwio"

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: Build tool
        run: cargo build ${{ matrix.features }} --release --manifest-path tool/Cargo.toml

  ec:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - vendor: novacustom
            model: nv4x_tgl
          - vendor: novacustom
            model: ns5x_tgl
          - vendor: novacustom
            model: nv4x_adl
          - vendor: novacustom
            model: ns5x_adl
          - vendor: novacustom
            model: v540tnx
          - vendor: novacustom
            model: v540tu
          - vendor: novacustom
            model: v560tnx
          - vendor: novacustom
            model: v560tu

    steps:
      - uses: actions/checkout@v4

      - name: Build firmware
        run: EC_BOARD_VENDOR=${{ matrix.vendor }} EC_BOARD_MODEL=${{ matrix.model }} ./build.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "dasharo-${{ matrix.vendor }}-${{ matrix.model }}"
          path: |
            ${{ matrix.vendor }}_${{ matrix.model }}_ec.rom
          retention-days: 30
