name: CI
on:
  push:
    branches: [master, ci]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check SPDX identifiers
        run: ./scripts/lint/spdx.sh
      - name: Check indentation
        run: ./scripts/lint/indent.sh

      - name: Check formatting
        run: ./scripts/clang-format.sh
        continue-on-error: true

  ec:
    runs-on: docker pull ghcr.io/dasharo/ec-sdk:main
    strategy:
      matrix:
        include:
          - vendor: novacustom
            board: nv4x_tgl
          - vendor: novacustom
            board: ns5x_tgl
          - vendor: novacustom
            board: nv4x_adl
          - vendor: novacustom
            board: ns5x_adl

    steps:
      - uses: actions/checkout@v2

      - name: Build firmware
        run: EC_BOARD_VENDOR=${{ matrix.vendor }} EC_BOARD_MODEL=${{ matrix.model }} ./build.sh
